version: 2.0

jobs:
  test:
    docker:
      - image: circleci/openjdk:stretch
    dependencies:
      pre:
        - sudo apt-get --reinstall install libept1.4.12
        - sudo apt-get install -y aptitude
        - sudo aptitude -y install imagemagick
        - sudo aptitude -y install libmagickcore-dev
        - sudo aptitude -y install libmagickwand-dev 
        - sudo apt-get install -y graphicsmagick 
    working_directory: ~/kp
    steps:
      - checkout
      - restore_cache:
          keys:
            - kp-jobs-dependency-cache-{{ checksum "pom.xml" }} # appends cache key with a hash of pom.xml fi
            - kp-jobs-dependency-cache- # fallback in case previous cache key is not foun
      - run: |
          ls /usr/lib/jvm/
          ls /usr/local/
          export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
          export PATH=$JAVA_HOME/bin:$PATH
          echo $PATH
          echo $JAVA_HOME
          mvn test
          # Commenting below code which used for parllel test run 
          # mvn -Dtest=$(for file in $(circleci tests glob "./**/src/test/**/spec/*.scala" \
          # |  circleci tests split --split-by=timings --timings-type=classname); \
          # do basename $file \
          # | sed -e "s/.scala/,/"; \
          # done | tr -d '\r\n') \
          # -e test
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - save_cache:
            paths:
              - ~/.m2
            key: kp-jobs-dependency-cache-{{ checksum "pom.xml" }}
      - store_test_results:
          path: ~/test-results
      - run:
           name: sonar
           command: |
             mvn -X sonar:sonar -Dlog4j.configuration=./logs sonar:sonar -Dsonar.projectKey=project-sunbird_knowledge-platform-jobs -Dsonar.organization=project-sunbird -Dsonar.host.url=https://sonarcloud.io -Dsonar.exclusions=**/cert-processor/** -Dsonar.scala.coverage.reportPaths=/home/circleci/kp/target/scoverage.xml
  build:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - kp-jobs-dependency-cache-{{ checksum "pom.xml" }} # appends cache key with a hash of pom.xml file
            - kp-jobs-dependency-cache- # fallback in case previous cache key is not foun
      - run: |
          ls /usr/lib/jvm/
          ls /usr/local/
          export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
          export PATH=$JAVA_HOME/bin:$PATH
          echo $PATH
          echo $JAVA_HOME
          mvn clean install -DskipTests
      - save_cache:
            paths:
              - ~/.m2
            key: kp-jobs-dependency-cache-{{ checksum "pom.xml" }}

workflows:
  version: 2
  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build